---
- name: Add monitoring user
  rabbitmq_user:
    user: 'monitoring'
    password: "{{ lookup('password', '' + ansible_hostname + ':backup length=12 chars=ascii_letters,digits') }}"
    tags: 'monitoring'
    vhost: '/'

- name: Add RabbitMQ prometheus exporter YUM repositories
  yum_repository:
    name: '{{ rabbitmq_exporter_repo_name }}'
    description: '{{ rabbitmq_exporter_repo_name }} YUM repository'
    file: '{{ rabbitmq_exporter_repo_name }}'
    baseurl: '{{ rabbitmq_exporter_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the RabbitMQ prometheus exporter
  yum:
    name: '{{ rabbitmq_exporter_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5

- name: Prometheus RabbitMQ exporter configure file transfer
  template:
    src: 'rabbitmq_exporter.j2'
    dest: '/etc/default/rabbitmq_exporter'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: conf_update

- name: RabbitMQ exporter service is enabled
  systemd:
    name: 'rabbitmq_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: yes
  when: conf_update is changed
