---
- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status
  include: 'selinux.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Configuration the RabbitMQ
  include: 'configureation.yml'

- name: Reload the RabbitMQ service
  shell: echo ''
  notify: 'Ensure RabbitMQ service is enabled'
  when:
    - rabbitmq_conf is changed or rabbitmq_update is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Include plugins tasks
  include: 'plugins.yml'

- name: Include authentication tasks
  include: 'authentication.yml'
  when: rabbitmq_bu_arg is defined

- name: Install RabbitMQ prometheus exporter
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool
