---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add EPEL YUM repositories.
  yum_repository:
    name: '{{ rabbitmq_epel_repo_name }}'
    description: '{{ rabbitmq_epel_repo_name }} YUM repo'
    file: '{{ rabbitmq_epel_repo_name }}'
    baseurl: '{{ rabbitmq_epel_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Add Erlang YUM repositories.
  yum_repository:
    name: '{{ rabbitmq_erlang_repo_name }}'
    description: '{{ rabbitmq_erlang_repo_name }} YUM repository'
    file: '{{ rabbitmq_erlang_repo_name }}'
    baseurl: '{{ rabbitmq_erlang_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Add RabbitMQ YUM repositories.
  yum_repository:
    name: '{{ rabbitmq_repo_name }}'
    description: '{{ rabbitmq_repo_name }} YUM repository'
    file: '{{ rabbitmq_repo_name }}'
    baseurl: '{{ rabbitmq_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the RabbitMQ packages.
  yum:
    name: '{{ rabbitmq_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: rabbitmq_update
  until: rabbitmq_update is succeeded
  retries: 5
  delay: 2
